import React, { useState } from 'react';
import { useAppDispatch,useAppSelector } from '../../../../store/hooks';
import { spaceActions } from '../../store/spaceSlice';
import { Panel } from '../hud/Panel';
export function GuestBook() {
 const {profile}=useAppSelector(s=>s.space),dispatch=useAppDispatch(),[message,setMessage]=useState('');
 return <Panel title="Little notes, warm hearts." eyebrow="GUEST BOOK / LOCAL PROTOTYPE" onClose={()=>dispatch(spaceActions.setPanel(null))}><p className="muted">Luna와 Nova는 예시 방문자입니다. 새 메시지는 이 기기에 저장돼요.</p><div className="guest-list">{profile.guests.map(e=><article key={e.id}><span className="guest-avatar">{e.avatar}</span><div><strong>{e.nickname}</strong><time>{new Date(e.createdAt).toLocaleDateString()}</time><p>{e.message}</p></div></article>)}</div><form onSubmit={e=>{e.preventDefault();if(!message.trim())return;dispatch(spaceActions.addGuest({id:crypto.randomUUID(),avatar:'✧',nickname:profile.character?.nickname??'Traveler',message:message.trim(),createdAt:new Date().toISOString()}));setMessage('');}}><label className="field-label" htmlFor="guest-message">LEAVE A MESSAGE</label><textarea id="guest-message" placeholder="Leave a message..." maxLength={280} value={message} onChange={e=>setMessage(e.target.value)} required/><div className="panel-actions"><button className="primary-button" disabled={!message.trim()}>POST ↗</button></div></form></Panel>;
}
export function PersonalBoard() {
 const {profile}=useAppSelector(s=>s.space),dispatch=useAppDispatch(),[selected,setSelected]=useState<string|null>(null),[writing,setWriting]=useState(false),[title,setTitle]=useState(''),[content,setContent]=useState(''),[comment,setComment]=useState('');
 const post=profile.posts.find(p=>p.id===selected);
 return <Panel title="Stories from my planet." eyebrow="PERSONAL BOARD" onClose={()=>dispatch(spaceActions.setPanel(null))}>
 {writing?<form onSubmit={e=>{e.preventDefault();if(!title.trim()||!content.trim())return;const id=crypto.randomUUID();dispatch(spaceActions.addPost({id,authorNickname:profile.character!.nickname,title:title.trim(),content:content.trim(),createdAt:new Date().toISOString(),likes:0,liked:false,comments:[]}));setSelected(id);setWriting(false);setTitle('');setContent('');}}><label className="field-label" htmlFor="post-title">TITLE</label><input id="post-title" maxLength={80} required value={title} onChange={e=>setTitle(e.target.value)}/><label className="field-label" htmlFor="post-content">YOUR STORY</label><textarea id="post-content" rows={6} maxLength={3000} required value={content} onChange={e=>setContent(e.target.value)}/><div className="panel-actions"><button type="button" className="quiet-button" onClick={()=>setWriting(false)}>Cancel</button><button className="primary-button" disabled={!title.trim()||!content.trim()}>Publish story</button></div></form>:post?<><button className="quiet-button" onClick={()=>setSelected(null)}>← All stories</button><article className="post-detail"><h3>{post.title}</h3><p className="muted">{post.authorNickname} · {new Date(post.createdAt).toLocaleDateString()}</p><p>{post.content}</p><button className="quiet-button" aria-pressed={post.liked} onClick={()=>dispatch(spaceActions.likePost(post.id))}>{post.liked?'♥':'♡'} {post.likes}</button></article><h3>Comments · {post.comments.length}</h3>{post.comments.map(c=><p key={c.id} className="comment"><strong>{c.nickname}</strong> {c.content}</p>)}<form onSubmit={e=>{e.preventDefault();if(!comment.trim())return;dispatch(spaceActions.addComment({postId:post.id,id:crypto.randomUUID(),content:comment.trim()}));setComment('');}}><input aria-label="Write a comment" placeholder="A little thought..." value={comment} onChange={e=>setComment(e.target.value)} maxLength={300}/><div className="panel-actions"><button className="primary-button" disabled={!comment.trim()}>Comment</button></div></form></>:<><div className="story-list">{profile.posts.length?profile.posts.map(p=><button key={p.id} onClick={()=>setSelected(p.id)}><span><strong>{p.title}</strong><small>{p.authorNickname} · {new Date(p.createdAt).toLocaleDateString()}</small></span><span>♡ {p.likes} ↗</span></button>):<div className="empty-state">✎<h3>Your first story starts here.</h3><p>오늘 당신의 작은 별에서 무슨 일이 있었나요?</p></div>}</div><div className="panel-actions"><button className="primary-button" onClick={()=>setWriting(true)}>Write a story ↗</button></div></>}
 </Panel>;
}
