import React from 'react';
import { Link } from 'react-router-dom';
import { useAppDispatch,useAppSelector } from '../../../../store/hooks';
import { spaceActions } from '../../store/spaceSlice';
import type { Interaction } from '../../types/space.types';
export function GameHud({onEnter,near,onInteract,onEdit}:{onEnter:()=>void;near:Interaction|null;onInteract:()=>void;onEdit:()=>void}) {
 const {profile,mode,editing,panel}=useAppSelector(s=>s.space),dispatch=useAppDispatch(),overview=mode==='SPACE';
 return <div className="space-hud"><header className="space-topbar"><Link to="/home" className="space-brand"><span>✳</span> polychat<span className="brand-dot">.</span></Link><div className="space-location"><span className="live-dot"/>{mode==='HOME'?'HOME SWEET HOME':'YOUR LITTLE UNIVERSE'}<small>LOCAL WORLD</small></div><div className="hud-actions"><button aria-label="Settings" title="Settings" onClick={()=>dispatch(spaceActions.setPanel('settings'))}>⚙</button>{profile.character&&<><button aria-label="Inventory" title="Inventory" onClick={()=>dispatch(spaceActions.setPanel('inventory'))}>▦</button><button aria-label="Character" title="Character" onClick={()=>dispatch(spaceActions.setPanel('character'))}>♙</button></>}<Link to="/home" className="exit-link" aria-label="Return to home">↗</Link></div></header>
 {profile.character&&<div className="profile-hud glass"><span className="profile-avatar">{profile.character.nickname.slice(0,1)}</span><div><strong>{profile.character.nickname}</strong><small>Lv. {profile.character.level} · STAR RESIDENT</small></div><span className="coin-balance">✦ {profile.currency.coins.toLocaleString()}</span></div>}
 {overview&&<><section className="space-intro"><p className="space-kicker">A SMALL PLANET. ENDLESS POSSIBILITIES.</p><h1>Your own<br/> little <em>universe.</em></h1><p>조금은 느리게, 조금 더 나답게.<br/>별들 사이, 당신만의 작은 세상을 만나세요.</p><div className="intro-line"/><div className="planet-coordinate"><span>01</span><div>MY LITTLE PLANET<small>{profile.character?`${profile.character.nickname}’s home among the stars`:'Somewhere wonderful begins with you.'}</small></div></div></section><div className="orbit-caption"><span>✧</span><p>YOUR WORLD IS WAITING<small>작은 별에 커다란 이야기를 담아보세요.</small></p></div><div className="enter-planet"><span className="orbit-hint">↔ DRAG TO ORBIT · SCROLL TO EXPLORE</span><button className="primary-button" onClick={onEnter}>{profile.character&&profile.selectedHome?'Enter your planet':'Start Your Planet'}<span>↗</span></button><p>{profile.character?'Welcome back, traveler.':'A little home. A new beginning.'}</p></div></>}
 {!overview&&profile.character&&<><div className="scene-toolbar"><button className="glass" onClick={()=>dispatch(spaceActions.setMode('SPACE'))}>◎ Space view</button>{mode==='HOME'&&!editing&&<button className="glass" onClick={onEdit}>✎ Edit Room</button>}</div><div className="emote-bar glass"><button onClick={()=>dispatch(spaceActions.setMotion('Wave'))}>♧ Wave</button><button onClick={()=>dispatch(spaceActions.setMotion('Sit'))}>⌑ Sit</button><button onClick={()=>dispatch(spaceActions.setMotion('Idle'))}>↟ Stand</button></div>{near&&!panel&&!editing&&(mode==='PLANET'||mode==='HOME')&&<button className="interaction-prompt glass" onClick={onInteract}><kbd>E</kbd><span>{near.label}</span><small>INTERACT</small></button>}</>}
 <footer className="space-footer"><span><i className="live-dot"/> A QUIET CORNER OF THE COSMOS</span><span>{overview?'EST. 2026 · MAKE YOURSELF AT HOME':'WASD / ↑↓←→ MOVE   ·   SHIFT RUN   ·   DRAG LOOK   ·   SCROLL ZOOM'}</span><span>✧ POLYCHAT SPACE</span></footer>
 </div>;
}

